# version: "3.8"
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./bms_backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: api

  frontend:
    build:
      context: ./bms_frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    tty: true
    command: '/bin/sh -c "curl -i -g -H\"Content-Type: application/json\" -d@book_data.json -XPOST http://backend:5000/api/new-books-data && /bin/sh"'

volumes:
  pgdata:
